### ISSUE TITLE
Вероятно не работает

### ISSUE THREAD

**Issue by oroscobob** [LinerSRT/n370b_n1#1]
Собрал с этого репозитария и с других твоих - собирается. (linaro 4.8 и 4.93). 

Не стартует (bootloop) ни с одной прошивкой из профильной темы на 4PDA, в том числе и с этой: lineage-14.1-20190212-UNOFFICIAL-n370b.zip

**Comment by LinerSRT** [comment]
Потому что это 3.18.35. А прошивки с шапки работают на ядре 3.18.19.
